### ISSUE TITLE
Create SPI for V2

### ISSUE THREAD

**Issue by kgudel** [cfpb/hmda-platform#2213]
To include the SPI in a deployment of keycloak using helm we need to create a docker image that contains the the spi jar and the modify our `values.yaml` file with the following (the below sample code is what I used to get the keycloak spi test working and so the directories used in the init container and that container image will change):

Add another `extraInitContainers`:
```
 - name: spi-provider
      image: kgudel/spi-provider:latest
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying SPI..."
          cp -rv /providers/authenticator/hmda/target/keycloak-authenticator-hmda-4.2.1.Final.jar /spi
      volumeMounts:
        - name: spi
          mountPath: /spi
```
Add to `cli.custom`:
```
/subsystem=keycloak-server/spi=form-action:add()
/subsystem=keycloak-server/spi=form-action/provider=registration-institution-action:add(properties={institutionSearchUri => "${env.INSTITUTION_SEARCH_URI}", institutionSearchValidateSsl => "${env.INSTITUTION_SEARCH_VALIDATE_SSL}"}, enabled=true)

```
Add another `extraVolumes`:
```
- name: spi
  mountPath: /opt/jboss/keycloak/standalone/deployments
```
