### ISSUE TITLE
add intermediate path ca to hmda applications

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-platform#4948]
Entrust intermediate is not added by default

Support for the Authority Information Access (AIA) Extension

Support for the caIssuers access method of the Authority Information Access extension is available. It is disabled by default for compatibility and can be enabled by setting the system property `com.sun.security.enableAIAcaIssuers` to the value `true`.

If set to true, Sun's PKIX implementation of CertPathBuilder uses the information in a certificate's AIA extension (in addition to CertStores that are specified) to find the issuing CA certificate, provided it is a URI of type ldap, http, or ftp.

**Comment by zencircle** [comment]
```
          env:
            - name: _JAVA_OPTIONS
              value: |
                -Dcom.sun.net.ssl.checkRevocation=false
```
